# fly.toml app configuration file generated for morning-bush-2183 on 2023-10-30T15:57:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morning-bush-2183"
primary_region = "arn"

[build]

[env]
  PORT = "3000" 

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
